[toolchain]
anchor_version = "0.31.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
universal_nft = "FXFjiHkZLqR9TWdGRcYAZPvFZLSXNrfKD3rwPTPoB8Xe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-node --transpile-only ./tests/universal_nft.ts"
